[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"

optimizer = true
optimizer_runs = 1_000_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "6APC1BZHY2WD813XUJ5RV6JWWFGW2B573W", url = "https://api-sepolia.basescan.org/api" }
